### ISSUE TITLE
Plan for moving server

### ISSUE THREAD

**Issue by hongquan** [voicerepublic/voicerepublic_dev#863]
We will move the current website to new server, to reduce cost. At this stage, we will keep the same version of the stack, because it is not possible now to upgrade the software components.

Let's figure out how the current website is setup, so that we don't lose any important thing when moving.

**Comment by hongquan** [comment]
The current server is running Debian 7, which still uses SysV for init. So all the startup scripts of the app are still in SysV style. This means we cannot move to a server with newer OS, which uses `systemd`. 

It is good that most of data stay in the same place, _/home/_ folder:

```
--- /home -----------------------
   41,9GiB [##########] /app
    8,4GiB [#         ] /backups
    8,2GiB [#         ] /postgres
  531,2MiB [          ] /backend
```

Init scrips:
- _/etc/init.d/rails-app_
- _/etc/init.d/rails-backend_

Some script is backing up Postgres every hour, but I don't know where the script is.

Their nginx config is saved in _/etc/nginx/sites-enabled_, not _/etc/nginx/sites-available_ as usual.

**Comment by munen** [comment]
@telmich Maybe you want to make a preemptive offer here? 

I’d guess that VR won’t be needing HA anymore. Also, it’s running the official instance of GPL software now instead of a proprietary platform. Maybe you could offer a different tariff for these reasons.

You’re the hosting master, but I’d say a customer retained is a customer gained.

**Comment by telmich** [comment]
@munen thanks for the pointer.

@hongquan Maybe you can join our chat at https://chat.ungleich.ch to discuss what you actually need.

**Comment by munen** [comment]
@telmich I suggest to add @mariobehling to the loop. Afaik he has budget control.

**Comment by hongquan** [comment]
Hix, which channel of https://chat.ungleich.ch/?

**Comment by mariobehling** [comment]
There is a voicerepublic channel, but I don't have access. My username is mariob.
