### ISSUE TITLE
Login to system currently not working

### ISSUE THREAD

**Issue by mariobehling** [voicerepublic/voicerepublic_dev#869]
Login to system using https://voicerepublic.com/users/sign_in is not possible. The login screen just appears again without any error message.

![Screenshot from 2019-09-09 17-04-00](https://user-images.githubusercontent.com/1583873/64542512-fd63c100-d323-11e9-8898-dd67ea28daf5.png)

**Comment by mariobehling** [comment]
If this was related to Cloudflare switching of the Cloudflare proxy should have solved it. I tried it, but problem is still there. Switched Cloudflare on again.

**Comment by fcartegnie** [comment]
Then this means the app isn't designed to provide cache hints to proxies.
There is not only a bug because of cached sessions, but potentially user session leak.
Switch it off for good.

**Comment by mariobehling** [comment]
Switch off Cloudflare? Ok. But, it does not solve the problem.

**Comment by mariobehling** [comment]
The last logins on the frontend were on 2019-08-29 15:48:39. Login to admin.voicerepublic.com are still possible.

**Comment by mariobehling** [comment]
Could it be related to the setup of https://blog.voicerepublic.com? I also added a certificate for the subdomain.

**Comment by mariobehling** [comment]
This issue was closed around the time that it stopped working: https://github.com/voicerepublic/voicerepublic_dev/issues/867

**Comment by fcartegnie** [comment]
that piece of **** does throw exception through another bug, in airbrake, which is disabled.
so we can't have proper log for our issue

And we can't fix that bug because it means upgrading airbrake, which we can't for now.

```
app@voicerepublic:~/app/current$ ./bin/rake airbrake:test
rake aborted!
Airbrake::Error: the 'default' notifier isn't configured
/home/app/app/shared/bundle/ruby/2.1.0/gems/airbrake-ruby-1.0.4/lib/airbrake-ruby.rb:288:in `call_notifier'
/home/app/app/shared/bundle/ruby/2.1.0/gems/airbrake-ruby-1.0.4/lib/airbrake-ruby.rb:238:in `build_notice'
/home/app/app/shared/bundle/ruby/2.1.0/gems/airbrake-5.0.4/lib/airbrake/rake/task_ext.rb:21:in `rescue in execute'
/home/app/app/shared/bundle/ruby/2.1.0/gems/airbrake-5.0.4/lib/airbrake/rake/task_ext.rb:19:in `execute'
Airbrake::Error: the 'default' notifier isn't configured
/home/app/app/shared/bundle/ruby/2.1.0/gems/airbrake-ruby-1.0.4/lib/airbrake-ruby.rb:288:in `call_notifier'
/home/app/app/shared/bundle/ruby/2.1.0/gems/airbrake-ruby-1.0.4/lib/airbrake-ruby.rb:151:in `notify_sync'
/home/app/app/shared/bundle/ruby/2.1.0/gems/airbrake-5.0.4/lib/airbrake/rake/tasks.rb:9:in `rescue in block (2 levels) in <top (required)>'
/home/app/app/shared/bundle/ruby/2.1.0/gems/airbrake-5.0.4/lib/airbrake/rake/tasks.rb:6:in `block (2 levels) in <top (required)>'
/home/app/app/shared/bundle/ruby/2.1.0/gems/airbrake-5.0.4/lib/airbrake/rake/task_ext.rb:19:in `execute'
StandardError: Exception from the test Rake task
/home/app/app/shared/bundle/ruby/2.1.0/gems/airbrake-5.0.4/lib/airbrake/rake/tasks.rb:7:in `block (2 levels) in <top (required)>'
/home/app/app/shared/bundle/ruby/2.1.0/gems/airbrake-5.0.4/lib/airbrake/rake/task_ext.rb:19:in `execute'
Tasks: TOP => airbrake:test
(See full trace by running task with --trace)
```

**Comment by fcartegnie** [comment]
Lack of config triggers the bug,
we need to re-enable airbrake/configure it
config/settings.local.yml
and config/initializers/errbit.rb

but disable it in its own configuration by adding production (live):

config.ignore_environments = %w(development test live)

c4208eafa0682cc96d7cc7ab556fcd79286177ea

**Comment by fcartegnie** [comment]
Now the real error on registration:

```
I, [2019-09-21T14:18:01.033602 #8749]  INFO -- : Completed 500 Internal Server Error in 2331ms
F, [2019-09-21T14:18:01.040273 #8749] FATAL -- : 
RestClient::NotFound (404 Not Found):
  app/middlewares/faye_auth.rb:11:in `call'
  app/middlewares/php_responder.rb:7:in `call'
  app/middlewares/streamboxx_endpoint.rb:13:in `call'
  app/middlewares/icebox_endpoint.rb:14:in `call'
  app/middlewares/backup.rb:4:in `call'
  app/middlewares/slides.rb:8:in `call'
  app/middlewares/media_tracker.rb:9:in `call'
  app/middlewares/tts.rb:4:in `call'
  app/middlewares/enforce_robots_txt.rb:29:in `call'

```

**Comment by fcartegnie** [comment]
ActionMailer issue. Disabling it works :/

**Comment by mariobehling** [comment]
> ActionMailer issue. Disabling it works :/

Well, we still need this mailer to reset accounts etc. right?

**Comment by fcartegnie** [comment]
https://github.com/mailgun/mailgun-ruby/issues/151
hardpatched because again... can't update for now
./app/shared/bundle/ruby/2.1.0/gems/mailgun_rails-0.8.0/lib/mailgun/client.rb
not fixed though

**Comment by fcartegnie** [comment]
patched eu server
./app/shared/bundle/ruby/2.1.0/gems/mailgun_rails-0.9.0/lib/mailgun/client.rb

**Comment by fcartegnie** [comment]
api key also replaced in production.rb
