### ISSUE TITLE
Requesting New Password shows 500 Error

### ISSUE THREAD

**Issue by mariobehling** [voicerepublic/voicerepublic_dev#871]
Requesting a new password at https://voicerepublic.com/users/password/new and clicking "Reset Password" results in Error 500.

![Screenshot from 2019-09-09 18-20-46](https://user-images.githubusercontent.com/1583873/64548368-c7780a00-d32e-11e9-8e02-0ce6147232e1.png)

**Comment by fcartegnie** [comment]
#869 duplicate
