### ISSUE TITLE
Change the color of MORE TALKS button

### ISSUE THREAD

**Issue by Dishebh** [voicerepublic/voicerepublic_dev#883]
### Description
Due to the similar color texture, the MORE TALKS button doesn't highlight properly. Change the color of the button to something that helps it highlight properly.

### Screenshot of the issue:
![Screenshot from 2019-12-25 21-51-06](https://user-images.githubusercontent.com/43489708/71448388-41f35b00-2761-11ea-817e-6b84f9b7d023.png)

**Comment by rishipurwar1** [comment]
Please assign me this issue.
I want to work on this issue if no one is working on it.

**Comment by Dishebh** [comment]
@Rishi007-web I guess the issue is already taken care of. Pls go ahead with some other issue. I am closing it as of now.
