### ISSUE TITLE
Facdebook login not working 

### ISSUE THREAD

**Issue by cggvuhh** [voicerepublic/voicerepublic_dev#894]
The Facebook login not working
![now 1](https://user-images.githubusercontent.com/68186540/92919884-ebdd5980-f44e-11ea-9a9e-2a77fcc0e9be.PNG)

@mariobehling @munen 
plz review this issue

**Comment by munen** [comment]
There’s not a lot to review. The feature is disabled since there’s no corresponding Fb app.

**Comment by cggvuhh** [comment]
### @munen  @branch14    is this project is active for contributions in CODEHEAT 2020 plz reply

**Comment by iamareebjamal** [comment]
@cggvuhh He already replied

**Comment by munen** [comment]
This is a question for Mario. Neither me nor branch14 are involved there.

**Comment by cggvuhh** [comment]
@munen @iamareebjamal i  cannot get the point this project is now closed ???
but this project include in codeheat list

**Comment by mariobehling** [comment]
The project is active. The chat channel for this project is https://gitter.im/VoiceRepublic/VoiceRepublic
Thanks

**Comment by mariobehling** [comment]
We are not using Facebook anymore.
